dependency-dir: ../lib

depends:
    - crc
    - serial-datagram:
        fork: Stapelzeiger
    - parameter:
        fork: Stapelzeiger
    - simplerpc
    - pid
    - arm-cortex-tools
    - timestamp
    - msgbus

target.arm:
    - src/main.c
    - src/panic_log.c
    - src/sntp/sntp.c
    - src/commands.c
    - src/rpc_server.c
    - src/rpc_callbacks.c
    - src/msg_callbacks.c
    - src/uavcan_node.cpp
    - src/blocking_uart_driver.c
    - src/config.c
    - src/interface_panel.c
    - src/motor_driver.c
    - src/motor_driver_uavcan.cpp
    - src/motor_manager.c
    - src/stream.c
    - src/malloc_lock.c
    - src/log.c
    - src/usbconf.c
    - src/aversive/math/fast_math/fast_math.c
    - src/aversive/math/geometry/circles.c
    - src/aversive/math/geometry/lines.c
    - src/aversive/math/geometry/polygon.c
    - src/aversive/math/geometry/vect_base.c
    - src/aversive/math/vect2/vect2.c
    - src/aversive/cvra/cvra_motors.c
    - src/aversive/cvra/cvra_pid.c
    - src/aversive/error/error.c
    - src/aversive/robot_system/angle_distance.c
    - src/aversive/robot_system/robot_system.c
    - src/aversive/position_manager/position_manager.c
    - src/aversive/quadramp/quadramp.c
    - src/aversive/control_system_manager/control_system_manager.c
    - src/aversive/trajectory_manager/trajectory_manager.c
    - src/aversive/trajectory_manager/trajectory_manager_core.c
    - src/aversive/trajectory_manager/trajectory_manager_utils.c
    - src/aversive/blocking_detection_manager/blocking_detection_manager.c
    - src/aversive/obstacle_avoidance/obstacle_avoidance.c
    - src/base/encoder.c
    - src/base/base_controller.c
    - src/config_msgpack.c

source:
    - src/unix_timestamp.c
    - src/bus_enumerator.c
    - src/trajectories.c
    - src/base/polar.c
    - src/base/odometry.c

include_directories:
    - src/
    - src/aversive/
    - src/board/

tests:
    - tests/ch.cpp
    - tests/log.c
    - tests/unix-timestamp.cpp
    - tests/bus_enumerator.cpp
    - tests/polar_test.cpp
    - tests/odometry_test.cpp

templates:
    app_src.mk.jinja: app_src.mk
    CMakeLists.txt.jinja: CMakeLists.txt
