clone:
  recursive: true

build:
  dockerfiles:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    commands:
      - cd ci/dockerfiles
      - ls /var/run/docker.sock
      - docker build -t cpputest cpputest

  master-firmware-tests:
    image: cpputest
    commands:
      - cd master-firmware
      - packager
      - mkdir build
      - cd build
      - cmake ..
      - make -j check

  motor-firmware-tests:
    image: cpputest
    commands:
      - cd motor-control-firmware
      - packager
      - mkdir build
      - cd build
      - cmake ..
      - make -j check
