clone:
  recursive: true

build:
  dockerfiles:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    commands:
      - cd ci/dockerfiles
      - ls /var/run/docker.sock
      - docker build -t cpputest cpputest
      - docker build -t gcc-arm-embedded gcc-arm-embedded

  master-firmware-tests:
    image: cpputest
    commands:
      - cd master-firmware
      - packager
      - mkdir build
      - cd build
      - cmake ..
      - make -j check

  motor-firmware-tests:
    image: cpputest
    commands:
      - cd motor-control-firmware
      - packager
      - mkdir build
      - cd build
      - cmake ..
      - make -j check

  master-firmware:
    image: gcc-arm-embedded
    commands:
      # Install UAVCAN dsdl compiler
      - cd $DRONE_DIR/lib/uavcan/libuavcan/dsdl_compiler/pyuavcan/
      - python3 setup.py install
      - cd $DRONE_DIR/lib/uavcan/libuavcan/dsdl_compiler/
      - python3 setup.py install

      - cd $DRONE_DIR/master-firmware
      - packager
      - make dsdlc
      - make -j

  motor-firmware:
    image: gcc-arm-embedded
    commands:
      # Install UAVCAN dsdl compiler
      - cd $DRONE_DIR/lib/uavcan/libuavcan/dsdl_compiler/pyuavcan/
      - python3 setup.py install
      - cd $DRONE_DIR/lib/uavcan/libuavcan/dsdl_compiler/
      - python3 setup.py install

      - cd $DRONE_DIR/motor-control-firmware
      - packager
      - make dsdlc
      - make -j

  can-io-firmware:
    image: gcc-arm-embedded
    commands:
      # Install UAVCAN dsdl compiler
      - cd $DRONE_DIR/lib/uavcan/libuavcan/dsdl_compiler/pyuavcan/
      - python3 setup.py install
      - cd $DRONE_DIR/lib/uavcan/libuavcan/dsdl_compiler/
      - python3 setup.py install

      - cd $DRONE_DIR/can-io-firmware
      - packager
      - make dsdlc
      - make -j
