sudo: false
dist: bionic

services:
  - docker

addons:
    apt:
        packages:
            - freeglut3-dev
            - libgpiod-dev
            - libsdl2-dev
            - protobuf-compiler
            - python
            - python-pip
            - python-virtualenv
            - python3-dev

language: cpp

matrix:
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="actuator"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="can-io"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="motor-control"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="proximity-beacon"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="sensor"
        - compiler: gcc
          env: BUILD_TYPE="build-packager" PLATFORM="uwb-beacon"


before_install:
    - git submodule update --init --recursive

install:
    - ci/install.sh

script:
    - ci/build.sh
