logging:
  # level can be "debug", "notice" "warning" or "error"
  uart:
    level: "notice"
  sdcard:
    level: "notice" # changing this to debug slows down things too much and causes panic
master:
    robot_size_x_mm: 205 # Front to back length
    robot_alignment_length_mm: 130 # robot length from center to alignement border
    opponent_size_x_mm_default: 300
    calibration_direction: 1 # calibration side is on the front
    odometry:
        external_encoder_ticks_per_mm: 162.974661726 # Computed 162.974661726
        external_track_mm: 193.50199890              # CAD 194
        left_wheel_correction_factor: -1.00028944
        right_wheel_correction_factor: 0.99971050
    beacon:
        reflector_radius: 0.04 # in meters
        angular_offset: -1.57 # in radians
    aversive:
        control:
            angle:
                kp: 3
                ki: 0.
                kd: 20.
                ilimit: 1000.
            distance:
                kp: 2.
                ki: 0.
                kd: 25.
                ilimit: 5000.
        trajectories:
            angle:
                speed: # in rad / s
                    init: 0.75
                    slow: 0.75
                    fast: 2.
                acceleration: # in rad / s^2
                    init: 1.57
                    slow: 1.57
                    fast: 10.
            distance:
                speed: # in m / s
                    init: 0.1
                    slow: 0.2
                    fast: 0.3
                acceleration: # in m / s^2
                    init: 0.15
                    slow: 0.5
                    fast: 1.
    left_arm:
        control:
            x:
                kp: 5.
                ki: 0.
                kd: 5
                ilimit: 100.
            y:
                kp: 5.
                ki: 0.
                kd: 5
                ilimit: 100.
            heading:
                kp: 10.
                ki: 0.
                kd: 0.
                ilimit: 100.
            pitch:
                kp: 0.
                ki: 0.
                kd: 0.
                ilimit: 100.
    right_arm:
        control:
            x:
                kp: 4.
                ki: 0.
                kd: 5.
                ilimit: 100.
            y:
                kp: 10.
                ki: 0.
                kd: 5.
                ilimit: 100.
            heading:
                kp: 40.
                ki: 0.
                kd: 100.
                ilimit: 100.
            pitch:
                kp: 10.
                ki: 0.
                kd: 0.
                ilimit: 100.
    arms:
        upperarm_length: 86. # in mm
        forearm_length: 43. # in mm
        wrist_to_hand_length: 55. # in mm
        left:
            offset_x: 0.   # in mm
            offset_y: 120. # in mm
            offset_a: 1.57 # in radians
        right:
            offset_x: 0.   # in mm
            offset_y: -120. # in mm
            offset_a: -1.57 # in radians
        motor_offsets:
            left-z: -154. # in mm
            left-shoulder: 0. # in radians
            left-elbow: 0. # in radians
            left-wrist-heading: 0. # in radians
            left-wrist-pitch: 0. # in radians
            right-z: -205. # in mm
            right-shoulder: 0. # in radians
            right-elbow: 0. # in radians
            right-wrist-heading: 0. # in radians
            right-wrist-pitch: 0. # in radians

actuator:
    left-wheel:
        stream:
            # Encoder position is needed for odometry
            encoder_pos: 0
            velocity_pid: 0
            position_pid: 0
        motor:
            mode: 2
            motor_encoder_steps_per_revolution: 4096
            second_encoder_steps_per_revolution: 16384
            transmission_ratio_p: 49
            transmission_ratio_q: 676
            torque_constant: 1.
        control:
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                ilimit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                ilimit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.

    right-wheel:
        stream:
            # Encoder position is needed for odometry
            encoder_pos: 0
            velocity_pid: 0
            position_pid: 0
        motor:
            mode: 2
            motor_encoder_steps_per_revolution: 4096
            second_encoder_steps_per_revolution: 16384
            transmission_ratio_p: 49
            transmission_ratio_q: 676
            torque_constant: 1.
        control:
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                ilimit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                ilimit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.

    left-z:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 10
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 4096
            # transmission: motor: 1/1 gears: 16/42
            transmission_ratio_p: 8
            transmission_ratio_q: 21
            torque_constant: 0.016 # Nm/A
        control:
            current:
                kp: 3.
                ki: 500.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.005
                ki: 0.2
                kd: 0.
                ilimit: 100.
            position:
                kp: 10.
                ki: 10.
                kd: 0.
                ilimit: 1000

            low_batt_th: 12
            acceleration_limit: 2500.
            velocity_limit: 2000.
            torque_limit: 1.3
    left-shoulder:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 50
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/80
            transmission_ratio_p: 1
            transmission_ratio_q: 304
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.2
                ki: 0.8
                kd: 0.
                ilimit: 0.13
            position:
                kp: 6
                ki: 1.
                kd: 2.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 1
    left-elbow:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 50
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/60
            transmission_ratio_p: 1
            transmission_ratio_q: 228
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 8
                ki: 1
                kd: 0.
                ilimit: 0.5
            position:
                kp: 12
                ki: 0.
                kd: 0.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 3
    left-wrist-down:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 50
            index: 0
        motor:
            # motor: 1524E012SR IE-512
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76
            transmission_ratio_p: 1
            transmission_ratio_q: 76
            torque_constant: 0.0115 # Nm/A
        control:
            current:
                kp: 22.
                ki: 6000.
                kd: 0.
                ilimit: 100.
            velocity:
                kp: 1
                ki: 20
                kd: 0.
                ilimit: 100
            position:
                kp: 5.
                ki: 1.
                kd: 0.
                ilimit: 10.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 10
            torque_limit: 5
    left-wrist-up:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 50
            index: 0
        motor:
            # motor: 1524E012SR IE-512
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76
            transmission_ratio_p: 1
            transmission_ratio_q: 76
            torque_constant: 0.0115 # Nm/A
        control:
            current:
                kp: 22.
                ki: 6000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 1
                ki: 20
                kd: 0.
                ilimit: 100
            position:
                kp: 5.
                ki: 1.
                kd: 0.
                ilimit: 10.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 10
            torque_limit: 5
    right-z:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 10
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 4096
            # transmission: motor: 1/1 gears: 16/42
            transmission_ratio_p: 8
            transmission_ratio_q: 21
            torque_constant: 0.016 # Nm/A
        control:
            current:
                kp: 2.
                ki: 400.
                kd: 0.
                ilimit: 25.
            velocity:
                kp: 0.01
                ki: 0.2
                kd: 0.
                ilimit: 100
            position:
                kp: 20
                ki: 50
                kd: 0
                ilimit: 1000
            low_batt_th: 12
            acceleration_limit: 500.
            velocity_limit: 500.
            torque_limit: 1.3
    right-shoulder:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 50
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/80
            transmission_ratio_p: 1
            transmission_ratio_q: 304
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 0
                ki: 10000.
                kd: 0.
                ilimit: 100.
            velocity:
                kp: 2
                ki: 50
                kd: 0.
                ilimit: 100
            position:
                kp: 40
                ki: 0
                kd: 0

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 1
    right-elbow:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 50
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/60
            transmission_ratio_p: 1
            transmission_ratio_q: 228
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 20.
                ki: 10000.
                kd: 0.
                ilimit: 200.
            velocity:
                kp: 5
                ki: 4
                kd: 0.
                ilimit: 100
            position:
                kp: 10
                ki: 0
                kd: 0.2
            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 3
    right-wrist:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 50
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # periodic
            motor_encoder_steps_per_revolution: 2048
            second_encoder_steps_per_revolution: 0
            # transmission: motor: 1/76 gears: 20/50
            transmission_ratio_p: 1
            transmission_ratio_q: 190
            torque_constant: 0.0115 # Nm/A
        control:
            current:
                kp: 20.
                ki: 500.
                kd: 0.
                ilimit: 100.
            velocity:
                kp: 10
                ki: 100
                kd: 0.
                ilimit: 100
            position:
                kp: 10
                ki: 0
                kd: 0

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 8.
            torque_limit: 1.3

    right-element-rotate:
        motor:
            mode: 0 # open loop mode
            transmission_ratio_p: 1
            transmission_ratio_q: 1
            torque_constant: 1. # Nm/A
        control:
            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 50.
            torque_limit: 5.
