actuator:
    theta-1:
    # motor: 1524SR
        streams:
            motor_pos: 50.
        encoders:
            primary:
                ticks_per_rev: 4096
                # transmission: motor: 5103/387283 env 1/76
                p: 1
                q: 76
        motor:
            current_offset: 0.0046 # A
            torque_cst: 0.0115 # Nm/A
        control:
            mode: 3 # bounded
            current:
                kp: 20.
                ki: 800.
                kd: 0.
                i_limit: 50.
    theta-2:
    # motor: 1524SR
        streams:
            motor_pos: 50.
        encoders:
            primary:
                ticks_per_rev: 2048
                # transmission: motor: 5103/387283 env 1/76
                p: 1
                q: 76
        motor:
            current_offset: 0.00695 # A
            torque_cst: 0.0115 # Nm/A
        control:
            mode: 3 # bounded
            current:
                kp: 20.
                ki: 800.
                kd: 0.
                i_limit: 50.
            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 1.
    theta-3:
    # motor: 1516SR
        streams:
            motor_pos: 50.
        encoders:
            primary:
                ticks_per_rev: 4096
                # transmission: motor: 5103/387283 env 1/76
                p: 1
                q: 76
        motor:
            current_offset: 0.00425 # A
            torque_cst: 0.00826 # Nm/A
        control:
            mode: 3 # bounded
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                i_limit: 100.
            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 1.
