master:
    odometry:
        wheelbase: 0.194
        radius_left: 0.016
        radius_right: 0.016
actuator:
    left-wheel:
        stream:
            velocity_pid: 100
        motor:
            mode: 3
            motor_encoder_steps_per_revolution: 4096
            second_encoder_steps_per_revolution: 16384
            transmission_ratio_p: 49
            transmission_ratio_q: 676
            torque_constant: 1.
        control:
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                ilimit: 50.

            velocity:
                kp: 1.
                ki: 8.
                kd: 0.
                ilimit: 100.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 1.

    right-wheel:
        stream:
            velocity_pid: 100
        motor:
            mode: 3
            motor_encoder_steps_per_revolution: 4096
            second_encoder_steps_per_revolution: 16384
            transmission_ratio_p: 49
            transmission_ratio_q: 676
            torque_constant: 1.
        control:
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                ilimit: 50.

            velocity:
                kp: 1.
                ki: 8.
                kd: 0.
                ilimit: 100.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 1.
