master:
    is_main_robot: true
    control_panel_active_high: false
    electron_uwb_mac: 42
    robot_size_x_mm: 260 # Robot diameter
    robot_alignment_length_mm: 135 # robot length from center to alignement border
    opponent_size_x_mm_default: 400
    calibration_direction: 1 # calibration side is on the front
    odometry:
        external_encoder_ticks_per_mm: 162.974661726 # Computed 162.974661726
        external_track_mm: 202.75294494
        left_wheel_correction_factor: 1.00038814    # Calibrated
        right_wheel_correction_factor: -0.99961113 # Calibrated
    beacon:
        reflector_radius: 0.04 # in meters
        angular_offset: 1.57 # in radians
    aversive:
        control:
            angle:
                kp: 4.
                ki: 0.
                kd: 25.
                i_limit: 10.
            distance:
                kp: 1.5
                ki: 0.5
                kd: 10.
                i_limit: 10.
        trajectories:
            angle:
                speed: # in rad / s
                    init: 0.75
                    slow: 0.75
                    fast: 3.
                acceleration: # in rad / s^2
                    init: 1.57
                    slow: 1.57
                    fast: 10.
            distance:
                speed: # in m / s
                    init: 0.1
                    slow: 0.2
                    fast: 0.5
                acceleration: # in m / s^2
                    init: 0.15
                    slow: 0.5
                    fast: 1.5
            windows:
                distance: 100.
                angle: 40.
                angle_start: 40.
    arms:
        right:
            lengths:
                origin: 0.2428
                l1: 0.132
                l2: 0.097
                l3: 0.072
            homing:
                q1: -0.40763
                q2: 1.53969
                q3: 0.0
            offsets: # calibrated before a game
                q1: 0.
                q2: 0.
                q3: 0.
            tolerance:
                q1: 0.02
                q2: 0.02
                q3: 0.02
            window:
                q1: 0.1
                q2: 0.1
                q3: 0.1
            gripper:
                release: 6.
                acquire: -14.
                current_thres: 0.24 # [A] pump current beyond which we consider the puck is picked
        left:
            lengths:
                origin: 0.2428
                l1: 0.132
                l2: 0.097
                l3: 0.072
            homing:
                q1: -0.40763
                q2: 1.53969
                q3: 0.0
            offsets: # calibrated before a game
                q1: 0.
                q2: 0.
                q3: 0.
            tolerance:
                q1: 0.02
                q2: 0.02
                q3: 0.02
            window:
                q1: 0.1
                q2: 0.1
                q3: 0.1
            gripper:
                release: -6.
                acquire: 14.
                current_thres: 0.24 # [A] pump current beyond which we consider the puck is picked
    screen:
        ax: 0.089231252
        ay: -0.001139728
        bx: 0.000522375
        by: 0.127720847
        cx: -22.532257080
        cy: -28.272106170

actuator:
    left-wheel:
        encoders:
          primary:
            p: 49
            q: 676
            ticks_per_rev: 4096
        motor:
            torque_cst: 1.
        control:
            mode: 2
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                i_limit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                i_limit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.
            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.
    right-wheel:
        encoders:
          primary:
            p: 49
            q: 676
            ticks_per_rev: 4096
        motor:
            torque_cst: 1.
        control:
            mode: 2
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                i_limit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                i_limit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.
            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.
