logging:
  # level can be "debug", "notice" "warning" or "error"
  uart:
    level: "notice"
  sdcard:
    level: "notice" # changing this to debug slows down things too much and causes panic
master:
    is_main_robot: true
    control_panel_active_high: false
    robot_size_x_mm: 260 # Robot diameter
    robot_alignment_length_mm: 135 # robot length from center to alignement border
    opponent_size_x_mm_default: 400
    calibration_direction: 1 # calibration side is on the front
    odometry:
        external_encoder_ticks_per_mm: 163.62917844 # Computed 162.974661726
        external_track_mm: 202.43815612
        left_wheel_correction_factor: 1.00033247    # Calibrated
        right_wheel_correction_factor: -0.99966681 # Calibrated
    beacon:
        reflector_radius: 0.04 # in meters
        angular_offset: 0. # in radians
    aversive:
        control:
            angle:
                kp: 4.
                ki: 0.3
                kd: 40.
                i_limit: 100.
            distance:
                kp: 2.
                ki: 0.01
                kd: 25.
                i_limit: 100.
        trajectories:
            angle:
                speed: # in rad / s
                    init: 0.75
                    slow: 0.75
                    fast: 3.
                acceleration: # in rad / s^2
                    init: 1.57
                    slow: 1.57
                    fast: 10.
            distance:
                speed: # in m / s
                    init: 0.1
                    slow: 0.2
                    fast: 0.5
                acceleration: # in m / s^2
                    init: 0.15
                    slow: 0.5
                    fast: 1.5
            windows:
                distance: 100.
                angle: 40.
                angle_start: 40.
    wrist:
        horizontal: 0.00077
        vertical: 0.00215
    lever:
        right:
            offset_x: 0.    # in mm
            offset_y: -217.5 # in mm
            offset_a: 0.    # in rad
            servo:
                deployed: 0.0008
                retracted: 0.00205
        left:
            offset_x: 0.    # in mm
            offset_y: 217.5 # in mm
            offset_a: 0.    # in rad
            servo:
                deployed: 0.00215
                retracted: 0.00083
    ballgun:
        servo:
            deployed_charge: 0.00145
            deployed_fully: 0.0010
            deployed: 0.0014
            retracted: 0.00185
            channel: 1
        turbine:
            arm: 0.00153
            charge: 0.0018
            fire: 0.00135
            slowfire: 0.0014
            channel: 0
        accelerator:
            mode: "velocity"
            charge: -100.
            fire: 200.
            slowfire: 80.
        sense:
            detect_on: true
            low_threshold: 2
            high_threshold: 3
    main_arm:
        control:
            x:
                kp: 3.
                ki: 0.
                kd: 0.
                i_limit: 100.
            y:
                kp: 3.
                ki: 0.
                kd: 0.
                i_limit: 100.
    arms:
        upperarm_length: 100. # in mm
        forearm_length: 98. # in mm
        main_arm:
            offset_x: -100.  # in mm
            offset_y: 0.     # in mm
            offset_a: 3.1415 # in radians
        motor_offsets:
            z-joint: -275. # in mm
            shoulder-joint: 0.054184257 # in radians
            elbow-joint: 0.014701783 # in radians
    screen:
        ax: 0.089231252
        ay: -0.001139728
        bx: 0.000522375
        by: 0.127720847
        cx: -22.532257080
        cy: -28.272106170

actuator:
    left-wheel:
        encoders:
          primary:
            p: 49
            q: 676
            ticks_per_rev: 4096
        motor:
            torque_cst: 1.
        control:
            mode: 2
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                i_limit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                i_limit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.
            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.

    right-wheel:
        encoders:
          primary:
            p: 49
            q: 676
            ticks_per_rev: 4096
        motor:
            torque_cst: 1.
        control:
            mode: 2
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                i_limit: 50.
            velocity:
                kp: 20.
                ki: 50.
                kd: 0.
                i_limit: 1000.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 200.
            velocity_limit: 50.
            torque_limit: 30.

    z-joint:
        streams:
            motor_pos: 50.
        motor:
            torque_cst: 0.016 # Nm/A
        encoders:
            primary:
                # motor: 1516SR
                ticks_per_rev: 4096
                # transmission: motor: 1/1 gears: 16/42
                p: 8
                q: 21
        control:
            mode: 3 # bounded
            current:
                kp: 3.
                ki: 500.
                kd: 0.
                i_limit: 100.
            velocity:
                kp: 0.005
                ki: 0.2
                kd: 0.
                i_limit: 100.
            position:
                kp: 10.
                ki: 10.
                kd: 0.
                i_limit: 1000.
            low_batt_th: 5.
            acceleration_limit: 2500.
            velocity_limit: 2000.
            torque_limit: 1.3
    shoulder-joint:
        streams:
            motor_pos: 50.
        encoders:
            primary:
                # motor: 1516SR
                ticks_per_rev: 4096
                # transmission: motor: 1/76 gears: 20/80
                p: 1
                q: 304
        motor:
            torque_cst: 0.00826 # Nm/A
        control:
            mode: 3 # bounded
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                i_limit: 100.
            velocity:
                kp: 0.2
                ki: 0.8
                kd: 0.
                i_limit: 0.13
            position:
                kp: 6.
                ki: 1.
                kd: 2.
            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 1.
    elbow-joint:
        streams:
            motor_pos: 50.
        motor:
            torque_cst: 0.00826 # Nm/A
        encoders:
            primary:
                # motor: 1516SR
                ticks_per_rev: 4096
                # transmission: motor: 1/76 gears: 20/60
                p: 1
                q: 228
        control:
            mode: 3 # bounded
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                i_limit: 100.
            velocity:
                kp: 8.
                ki: 1.
                kd: 0.
                i_limit: 0.5
            position:
                kp: 12
                ki: 0.
                kd: 0.
            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 10.
            torque_limit: 3.
    arm-pump:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
    right-pump-1:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
    right-pump-2:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
    left-pump-1:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
    left-pump-2:
        control:
            mode: 0 # openloop
            low_batt_th: 5.
    ball-accelerator:
        encoders:
          primary:
            p: 1
            q: 1
            ticks_per_rev: 4096
        motor:
            torque_cst: 17.3
        control:
            mode: 2
            current:
                kp: 1.
                ki: 150.
                kd: 0.
                i_limit: 100.
            velocity:
                kp: 0.5
                ki: 150.
                kd: 0.
                i_limit: 100.
            low_batt_th: 5.
            acceleration_limit: 5000.
            velocity_limit: 550.
            torque_limit: 40.
