site_name: CVRA Robot Software
theme:
  name: gitbook
plugins: []
nav:
  - Home: index.md
  - Robot architecture:
    - '2020 hardware architecture': architecture/hardware2020.md
    - 'Life of a motion': architecture/life-of-a-motion.md
  - CAN:
      - 'CAN Ecosystem': can/intro.md
      - can/motor.md
      - can/io.md
      - can/sensor.md
      - can/beacon.md
      - can/adapter.md
      - can/bootloader.md
  - Systems:
      - can/positioning.md
