site_name: CVRA Robot Software
theme:
  name: gitbook
plugins: []
markdown_extensions:
  - codehilite:
      guess_lang: False

extra_css:
  - ytvideo.css
  - styles.css

nav:
  - Home: index.md
  - Robot architecture:
    - 'History & Design': architecture/history.md
    - '2020 hardware architecture': architecture/hardware2020.md
    - 'Life of a motion': architecture/life-of-a-motion.md
    - 'Master firmware on Linux': design/linux-master.md
  - 'How to':
    - 'Calibrate the odometry': howto/calibrate-odometry.md
    - howto/add_a_uavcan_message.md
    - howto/install_arm_gcc.md
  - Systems:
      - can/positioning.md
  - CAN:
      - 'CAN Ecosystem': can/intro.md
      - can/motor.md
      - can/io.md
      - can/sensor.md
      - can/beacon.md
      - can/adapter.md
      - can/bootloader.md
