depends:
    - crc

target.arm:
    - src/main.c
    - src/panic_log.c
    - src/sntp/sntp.c
    - src/commands.c
    - src/board/board.c

source:
    - src/timestamp.c

include_directories:
    - src/
    - src/board/


tests:
    - tests/unix-timestamp.cpp

templates:
    app_src.mk.jinja: app_src.mk
