dependency-dir: ./src
include_directories:
  - src/

depends:
  - crc
  - cmp
  - cmp_mem_access
  - test-runner
  - msgbus
  - parameter
  - chibios-syscalls

target.arm:
  - src/board.c
  - src/usbconf.c
  - src/cmd.c
  - src/main.c
  - src/bootloader_config.c
  - src/can-bootloader/config.c
  - src/exti.c
  - src/imu_thread.c
  - src/ahrs_thread.c
  - src/uavcan/uavcan_node.cpp
  - src/uavcan/imu_publisher.cpp
  - src/uavcan/parameter_server.cpp

source:
  - src/mpu9250.c
  - src/MadgwickAHRS.c

tests:
  - tests/mpu9250.cpp
  - tests/hal_mocks.cpp

templates:
  app_src.mk.jinja: app_src.mk
  include_dirs_tests.cmake.jinja: CMakeLists.txt
