dependency-dir: ./src

depends:
  - crc
  - cmp
  - cmp_mem_access
  - test-runner

target.arm:
  - src/board.c
  - src/usbconf.c
  - src/cmd.c
  - src/main.c
  - src/bootloader_config.c
  - src/can-bootloader/config.c

include_directories:
    - src/

source:
  - src/mpu9250.c

tests:
  - tests/mpu9250/init.cpp
  - tests/hal_mocks.cpp

templates:
  app_src.mk.jinja: app_src.mk
