dependency-dir: ./src

# depends:
#     -

target.arm:
    - src/board.c
    - src/usbconf.c
    - src/cmd.c
    - src/mpu9250.c
    - src/main.c

# source:
#     -

include_directories:
    - src/

# tests:
#     -

templates:
    app_src.mk.jinja: app_src.mk
