dependency-dir: ./src

depends:
  - crc
  - cmp
  - cmp_mem_access
  - test-runner
  - msgbus

target.arm:
  - src/board.c
  - src/usbconf.c
  - src/cmd.c
  - src/main.c
  - src/bootloader_config.c
  - src/can-bootloader/config.c
  - src/exti.c
  - src/imu_thread.c

include_directories:
  - src/

source:
  - src/mpu9250.c

tests:
  - tests/mpu9250.cpp
  - tests/hal_mocks.cpp

templates:
  app_src.mk.jinja: app_src.mk
  include_dirs_tests.cmake.jinja: CMakeLists.txt
