dependency-dir: ./src/

target.arm:
    - src/main.c
    - src/blocking_uart_driver.c
    - src/control.c
    - src/encoder.c
    - src/motor_pwm.c
    - src/analog.c
    - src/cmp.c

depends:
    - pid
    - serial-datagram
    - cmp_mem_access

#tests:

templates:
    Makefile.include.jinja: src/src.mk
