depends:
    - crc

target.arm:
    - main.c
    - panic_log.c
    - sntp/sntp.c
    - commands.c
    - usb_shell.c

source:
    - timestamp.c

tests:
    - tests/unix-timestamp.cpp

templates:
    app_src.mk.jinja: app_src.mk
