dependency-dir: ./src
include_directories:
  - src/
  - src/eigen

depends:
  - crc
  - cmp
  - cmp_mem_access
  - test-runner
  - msgbus
  - parameter
  - parameter_flash_storage
  - chibios-syscalls

target.arm:
  - src/board.c
  - src/usbconf.c
  - src/cmd.c
  - src/main.c
  - src/bootloader_config.c
  - src/can-bootloader/config.c
  - src/exti.c
  - src/imu_thread.c
  - src/ahrs_thread.c
  - src/uavcan/uavcan_node.cpp
  - src/uavcan/topics_publisher.cpp
  - src/uavcan/parameter_server.cpp
  - src/decawave_interface.c
  - src/ranging_thread.c
  - src/parameter_port.c

target.stm32f4: []

source:
  - src/mpu9250.c
  - src/MadgwickAHRS.c
  - src/decadriver/deca_device.c
  - src/decadriver/deca_params_init.c
  - src/uwb_protocol.c

tests:
  - tests/mpu9250.cpp
  - tests/hal_mocks.cpp
  - tests/decawave.cpp
  - tests/uwb_protocol.cpp
  - tests/ekf.cpp

templates:
  app_src.mk.jinja: app_src.mk
  include_dirs_tests.cmake.jinja: CMakeLists.txt
