dependency-dir: ../lib

depends:
    - crc
    - parameter
    - pid
    - arm-cortex-tools
    - timestamp
    - error
    - quadramp

target.arm:
    - src/main.c
    - src/debug/panic_log.c
    - src/debug/log.c
    - src/debug/blocking_uart.c
    - src/commands.c
    - src/config.c
    - src/can/uavcan_node.cpp
    - src/can/motor_driver.c
    - src/can/motor_driver_uavcan.cpp
    - src/can/motor_manager.c
    - src/malloc_lock.c
    - src/usbconf.c
    - src/pca9685_pwm.c
    - src/parameter_port.c

source:
    - src/unix_timestamp.c
    - src/can/bus_enumerator.c

include_directories:
    - src/
    - src/board/
    - src/debug/
    - src/can/

tests:
    - tests/ch.cpp
    - tests/bus_enumerator.cpp
    - tests/unix-timestamp.cpp

templates:
    app_src.mk.jinja: app_src.mk
    CMakeLists.txt.jinja: CMakeLists.txt
