dependency-dir: ../lib

source:
  - src/pressure_sensor.c
  - src/softspi.c

depends:
  - chibios-syscalls
  - cmp
  - cmp_mem_access
  - error
  - crc
  - version
  - quadramp

target.arm:
  - ../lib/can-bootloader/config.c
  - src/analog_input.c
  - src/board.c
  - src/bootloader_config.c
  - src/debug.c
  - src/main.c
  - src/pressure_sensor_interface.c
  - src/pump.c
  - src/pwm.c
  - src/safety.c
  - src/servo.c
  - src/uavcan/Command_handler.cpp
  - src/uavcan/feedback_publisher.cpp
  - src/uavcan/node.cpp

tests:
  - tests/pressure_sensor_driver_test.cpp
  - tests/softspi_test.cpp

templates:
    app_src.mk.jinja: app_src.mk
